import Foundation

/// One-shot tagger that maps existing untagged cards to a JLPT level using a
/// curated N5 seed dictionary.
///
/// Pure function — no I/O, no side effects. Returns a new `[CardDTO]` array
/// with `jlptLevel` populated where the card's `front` matches a known N5
/// vocabulary or kanji entry. Cards that already have a `jlptLevel` are
/// preserved unchanged (no overwrite). Grammar and listening cards are not
/// tagged via this service.
///
/// The seed is sourced from `Ikeru/Resources/ContentBundles/n5-content.sqlite`
/// (the canonical N5 content bundle: 205 vocabulary entries + 90 kanji
/// characters). Embedding the seed as static `Set<String>` avoids the
/// SQLite read on app launch and keeps the tagger pure.
public enum JLPTBackfillService {

    /// Returns a copy of `cards` with `jlptLevel` populated where the front
    /// matches a known N5 seed entry.
    public static func tag(cards: [CardDTO]) -> [CardDTO] {
        cards.map { card in
            guard card.jlptLevel == nil else { return card }
            guard N5SeedDictionary.contains(front: card.front, type: card.type) else {
                return card
            }
            return card.with(jlptLevel: .n5)
        }
    }
}

// MARK: - CardDTO copy helper

extension CardDTO {
    /// Returns a copy of this DTO with the given JLPT level. Used by
    /// `JLPTBackfillService` to produce new tagged copies without mutating
    /// the source.
    func with(jlptLevel: JLPTLevel?) -> CardDTO {
        CardDTO(
            id: id,
            front: front,
            back: back,
            type: type,
            fsrsState: fsrsState,
            easeFactor: easeFactor,
            interval: interval,
            dueDate: dueDate,
            lapseCount: lapseCount,
            leechFlag: leechFlag,
            jlptLevel: jlptLevel
        )
    }
}

// MARK: - N5 Seed Dictionary

/// Authoritative N5 vocabulary and kanji sets, extracted from the
/// `n5-content.sqlite` content bundle (205 vocab + 90 kanji).
private enum N5SeedDictionary {

    static func contains(front: String, type: CardType) -> Bool {
        switch type {
        case .vocabulary: return vocabulary.contains(front)
        case .kanji: return kanji.contains(front)
        case .grammar, .listening: return false
        }
    }

    /// 205 N5 vocabulary entries (word forms as they appear in the
    /// content bundle). Includes kana-only words like ありがとう and
    /// すみません because they ARE part of the N5 vocab list — they're
    /// vocabulary entries, distinct from raw kana mastery.
    static let vocabulary: Set<String> = [
        "ありがとう",
        "ある",
        "いい",
        "いる",
        "お母さん",
        "お父さん",
        "お茶",
        "お金",
        "お願いします",
        "ご飯",
        "すみません",
        "パン",
        "一つ",
        "七つ",
        "万",
        "三つ",
        "上",
        "下",
        "中",
        "九つ",
        "二つ",
        "五つ",
        "人",
        "今",
        "今年",
        "今日",
        "今月",
        "今週",
        "休む",
        "会う",
        "会社",
        "住む",
        "何",
        "作る",
        "使う",
        "便利",
        "元気",
        "兄",
        "先月",
        "先生",
        "先週",
        "入る",
        "八つ",
        "六つ",
        "円",
        "写真",
        "出かける",
        "出る",
        "分",
        "分かる",
        "前",
        "勉強",
        "北",
        "十",
        "千",
        "午前",
        "午後",
        "半",
        "南",
        "卵",
        "去年",
        "友達",
        "古い",
        "右",
        "名前",
        "四つ",
        "国",
        "土曜日",
        "外",
        "外国",
        "多い",
        "夜",
        "大きい",
        "大丈夫",
        "大切",
        "大学",
        "大学生",
        "天気",
        "女の人",
        "女の子",
        "妹",
        "姉",
        "始まる",
        "子供",
        "学校",
        "学生",
        "安い",
        "家",
        "家族",
        "寒い",
        "小さい",
        "少ない",
        "山",
        "川",
        "左",
        "帰る",
        "広い",
        "店",
        "弟",
        "待つ",
        "後ろ",
        "忙しい",
        "思う",
        "悪い",
        "手紙",
        "持つ",
        "教える",
        "新しい",
        "新聞",
        "日曜日",
        "日本",
        "日本人",
        "日本語",
        "早い",
        "明るい",
        "明日",
        "易しい",
        "映画",
        "昨日",
        "昼",
        "昼ご飯",
        "時間",
        "晩ご飯",
        "暑い",
        "暖かい",
        "暗い",
        "書く",
        "月曜日",
        "有名",
        "朝",
        "朝ご飯",
        "木",
        "木曜日",
        "本",
        "来る",
        "来年",
        "来月",
        "来週",
        "東",
        "果物",
        "楽しい",
        "歩く",
        "母",
        "毎年",
        "毎日",
        "毎月",
        "毎朝",
        "毎週",
        "水",
        "水曜日",
        "泳ぐ",
        "涼しい",
        "火曜日",
        "父",
        "狭い",
        "男の人",
        "男の子",
        "病院",
        "白い",
        "百",
        "知る",
        "空",
        "立つ",
        "終わる",
        "聞く",
        "肉",
        "自転車",
        "花",
        "花見",
        "英語",
        "行く",
        "西",
        "見る",
        "言う",
        "話す",
        "読む",
        "買う",
        "走る",
        "車",
        "軽い",
        "近い",
        "遅い",
        "遠い",
        "部屋",
        "重い",
        "野菜",
        "金曜日",
        "銀行",
        "長い",
        "閉める",
        "開ける",
        "難しい",
        "雨",
        "電話",
        "電車",
        "静か",
        "面白い",
        "音楽",
        "食べる",
        "食べ物",
        "飲み物",
        "飲む",
        "駅",
        "高い",
        "魚",
    ]

    /// 90 N5 kanji characters.
    static let kanji: Set<String> = [
        "一",
        "七",
        "万",
        "三",
        "上",
        "下",
        "中",
        "九",
        "二",
        "五",
        "人",
        "今",
        "休",
        "何",
        "先",
        "入",
        "八",
        "六",
        "円",
        "出",
        "分",
        "前",
        "北",
        "十",
        "千",
        "半",
        "南",
        "友",
        "古",
        "右",
        "名",
        "四",
        "国",
        "土",
        "外",
        "多",
        "大",
        "天",
        "女",
        "子",
        "学",
        "安",
        "小",
        "少",
        "山",
        "川",
        "左",
        "年",
        "後",
        "手",
        "新",
        "日",
        "時",
        "書",
        "月",
        "木",
        "本",
        "来",
        "東",
        "校",
        "母",
        "毎",
        "気",
        "水",
        "火",
        "父",
        "生",
        "男",
        "白",
        "百",
        "空",
        "立",
        "聞",
        "花",
        "行",
        "西",
        "見",
        "話",
        "語",
        "読",
        "買",
        "車",
        "金",
        "長",
        "間",
        "雨",
        "電",
        "食",
        "飲",
        "高",
    ]
}
