-- Baseline schema for the Ikeru sync backend (GAP-14).
--
-- ---------------------------------------------------------------------------
-- WHY THIS FILE EXISTS, AND WHY IT IS DATED BEFORE THE MIGRATION NEXT TO IT
-- ---------------------------------------------------------------------------
--
-- The 8 sync tables were created by hand in the Supabase dashboard during
-- cloud-sync lot 1. Only one migration was ever written down — the composite
-- primary key fix of 2026-08-14 — which meant `supabase/migrations/` described
-- an ALTER to tables the repository had no definition for. Recreating this
-- backend from the repo was impossible, and the free tier pauses a project
-- after ~7 days of inactivity: the day a restore goes wrong, the schema lives
-- nowhere but in a dashboard.
--
-- This file is that missing definition, reconstructed on 2026-08-15 by
-- introspecting the live project (`information_schema.columns`, `pg_policies`,
-- `pg_indexes`, `pg_constraint`, `information_schema.triggers`, `pg_proc`).
-- It is deliberately timestamped BEFORE `20260814140000_composite_pk_user_id_id`
-- so a replay runs create-then-alter in the order history actually happened.
--
-- ⚠️ It therefore reproduces the ORIGINAL single-column primary key. That is
-- not an oversight: the next migration is what turns it into `(user_id, id)`,
-- and it carries the full explanation of why. Do not "fix" this file to skip
-- ahead — you would make the migration that follows fail.
--
-- ⚠️ `IF NOT EXISTS` throughout, and every policy dropped before being
-- recreated, so replaying this against the live project is a no-op rather than
-- an error. It has NOT been run against the live project — it was written from
-- it. Verify on a branch database before trusting it for a restore.
--
-- Not covered here (they belong to Supabase's own managed schemas, not ours):
-- the `auth` schema, and the `rls_auto_enable` event trigger, which is a
-- project-level Supabase guard rather than application schema.

-- ---------------------------------------------------------------------------
-- Server clock
-- ---------------------------------------------------------------------------
--
-- `server_updated_at` is the column the pull paginates on, and it must be the
-- SERVER's clock — never the client's. A phone with a wrong date would
-- otherwise be able to write a cursor position into the past (rows skipped
-- forever) or the future (rows re-delivered forever). The trigger below is
-- what makes that guarantee hold no matter what a client sends.
--
-- `search_path` is pinned to the empty string: a SECURITY-sensitive function
-- that resolves names through a caller-controlled search path is a known
-- privilege-escalation shape.

create or replace function public.touch_server_updated_at()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  new.server_updated_at := now();
  return new;
end;
$function$;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
--
-- Shape shared by all 8:
--   id                 uuid, generated by the CLIENT (SwiftData model id)
--   user_id            uuid, DEFAULT auth.uid() — the client never sends it.
--                      A client-supplied user_id that disagreed with the
--                      bearer token would be a hazard worth removing entirely,
--                      so the column fills itself from the verified JWT.
--   payload            jsonb — the model, versioned by the app, not by DDL.
--                      Adding a field to a Swift model must not require a
--                      migration; that is the whole point of the jsonb blob.
--   updated_at         client clock (merge input — see SyncMergeRules)
--   deleted_at         tombstone (null = alive)
--   server_updated_at  server clock (cursor — never the client's)
--
-- ON DELETE CASCADE to auth.users is what makes account deletion complete:
-- removing the auth user removes every row it owns, including in tables added
-- after the deletion Edge Function was written.

create table if not exists public.profiles (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

create table if not exists public.rpg_states (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  profile_id        uuid,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

create table if not exists public.cards (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  profile_id        uuid,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

-- `review_logs` promotes four fields out of the jsonb payload into real
-- columns. `occurred_at` and `grade` because the FSRS replay orders and
-- applies on them; `answered_value`, `exercise_type` and `surface` because
-- confusion-pair telemetry queries them directly (lot 1) and a jsonb probe
-- per row would not scale.
create table if not exists public.review_logs (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  card_id           uuid,
  occurred_at       timestamptz not null,
  grade             smallint,
  answered_value    text,
  exercise_type     text,
  surface           text,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

create table if not exists public.vocabulary_entries (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  profile_id        uuid,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

create table if not exists public.vocabulary_encounters (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  entry_id          uuid,
  occurred_at       timestamptz,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

create table if not exists public.exercise_outcome_logs (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  profile_id        uuid,
  occurred_at       timestamptz,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

create table if not exists public.companion_chat_messages (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  profile_id        uuid,
  occurred_at       timestamptz,
  payload           jsonb not null,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (id)
);

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array[
    'profiles', 'rpg_states', 'cards', 'review_logs',
    'vocabulary_entries', 'vocabulary_encounters',
    'exercise_outcome_logs', 'companion_chat_messages'
  ] loop
    execute format(
      'drop trigger if exists %I on public.%I', t || '_touch_server_updated_at', t);
    execute format(
      'create trigger %I before insert or update on public.%I
         for each row execute function public.touch_server_updated_at()',
      t || '_touch_server_updated_at', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
--
-- This is what makes the publishable key safe to ship inside the app binary.
-- The key identifies the project, it grants nothing: every row carries
-- `user_id`, and every policy compares it to `auth.uid()` from the caller's
-- own verified JWT. Verified for real on 2026-08-13 — a second anonymous user
-- can neither read nor modify the first one's rows.
--
-- The `with_check` on INSERT/UPDATE is not redundant with the `using` clause:
-- `using` decides which rows you may touch, `with_check` decides what the row
-- may look like afterwards. Without it a caller could update a row they own
-- and hand it to somebody else by rewriting `user_id`.

do $$
declare t text;
begin
  foreach t in array array[
    'profiles', 'rpg_states', 'cards', 'review_logs',
    'vocabulary_entries', 'vocabulary_encounters',
    'exercise_outcome_logs', 'companion_chat_messages'
  ] loop
    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists %I on public.%I', t || '_select_own', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert_own', t);
    execute format('drop policy if exists %I on public.%I', t || '_update_own', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete_own', t);

    execute format(
      'create policy %I on public.%I for select using (auth.uid() = user_id)',
      t || '_select_own', t);
    execute format(
      'create policy %I on public.%I for insert with check (auth.uid() = user_id)',
      t || '_insert_own', t);
    execute format(
      'create policy %I on public.%I for update using (auth.uid() = user_id) with check (auth.uid() = user_id)',
      t || '_update_own', t);
    execute format(
      'create policy %I on public.%I for delete using (auth.uid() = user_id)',
      t || '_delete_own', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
--
-- `(user_id, server_updated_at)` is the cursor walk of the original pull.
-- The composite-key migration adds `(user_id, server_updated_at, id)` on top,
-- for the keyset pagination that came later. Both are kept: this file
-- reproduces history, it does not tidy it.

do $$
declare t text;
begin
  foreach t in array array[
    'profiles', 'rpg_states', 'cards', 'review_logs',
    'vocabulary_entries', 'vocabulary_encounters',
    'exercise_outcome_logs', 'companion_chat_messages'
  ] loop
    execute format(
      'create index if not exists %I on public.%I (user_id, server_updated_at)',
      t || '_user_cursor_idx', t);
  end loop;
end $$;

-- Replaying an FSRS card means fetching its logs; without this the query is a
-- scan of the user's whole log table per card.
create index if not exists review_logs_user_card_idx
  on public.review_logs (user_id, card_id);

-- Confusion-pair telemetry (lot 1) reads only rows that recorded what the
-- learner actually answered — a partial index keeps it off the rest.
create index if not exists review_logs_confusion_idx
  on public.review_logs (user_id, answered_value)
  where answered_value is not null;
