-- `text_imports` — the texts the learner brings in themselves.
--
-- ---------------------------------------------------------------------------
-- WHY THIS TABLE EXISTS
-- ---------------------------------------------------------------------------
--
-- « Apporte ton propre texte » (app-review-notes/08-vision-texte-perso.md):
-- the learner pastes or photographs some Japanese, picks the words they don't
-- know, and those become SRS cards that KEEP the sentence they came from.
--
-- Nico's ruling, 2026-08-19: that text IS backed up. A reinstall restores the
-- cards *with* their original sentence — which is only possible if the text
-- itself travels. `docs/privacy.html` was updated in the SAME change that
-- created this table, not after it: the page previously promised that "les
-- phrases d'exemple dans lesquelles vous avez rencontré un mot" never leave
-- the device, and shipping this table without rewriting that sentence would
-- have made the privacy policy false the day it deployed.
--
-- ---------------------------------------------------------------------------
-- WHY THERE IS NO `payload` COLUMN — the one deliberate divergence
-- ---------------------------------------------------------------------------
--
-- The 8 baseline tables carry a `payload jsonb` blob so a Swift model can gain
-- a field without a DDL migration, plus a handful of columns promoted out of it
-- for things the server actually queries or orders on.
--
-- This table promotes EVERYTHING, and keeps no blob. `TextImport` has six
-- business fields and they are all first-class: `content` is the whole point of
-- the feature (règle: le texte de l'utilisateur n'est jamais réécrit ni
-- tronqué — a column makes that inspectable, a blob hides it), `entry_ids` is
-- the link to the vocabulary the text produced, `coverage` is a frozen
-- snapshot the reading journal reads back. There is no residue left to put in a
-- blob, so adding an empty one would be cargo cult.
--
-- ⚠️ The consequence for anyone extending this: a new field on `TextImport`
-- DOES need a migration here. That is the trade — accepted knowingly, and the
-- reason it is written down.
--
-- Everything else is copied from the baseline exactly: composite primary key
-- `(user_id, id)`, `user_id` defaulting to `auth.uid()` and cascading from
-- `auth.users`, the four RLS policies, the `server_updated_at` trigger, and the
-- keyset index the pull paginates on.
--
-- `IF NOT EXISTS` / `drop policy if exists` throughout, same as the baseline,
-- so replaying this is a no-op rather than an error.

-- ---------------------------------------------------------------------------
-- Table
-- ---------------------------------------------------------------------------
--
--   id                 uuid, generated by the CLIENT (`TextImport.id`)
--   user_id            uuid, DEFAULT auth.uid() — the client NEVER sends it,
--                      exactly as for the 8 baseline tables. A client-supplied
--                      user_id disagreeing with the bearer token would be a
--                      hazard worth removing entirely, so the column fills
--                      itself from the verified JWT.
--   title              short label derived from the first line, for lists
--   content            the text AS THE LEARNER LEFT IT — including any
--                      correction they made to what the OCR read. Never
--                      re-derived, never truncated.
--   source             'paste' | 'photo' — kept as text, not an enum type: a
--                      future app version adding a third door must not need a
--                      server migration before it can back anything up, and an
--                      old client reading an unknown value keeps it verbatim
--                      (see `applyTextImportRows`, which writes
--                      `sourceRawValue` rather than round-tripping the enum).
--   created_at         when the learner imported it (client clock)
--   coverage           0…1 share of content words already known AT IMPORT
--                      TIME, nullable when there was nothing measurable to
--                      count. Frozen on purpose — recomputing it would rewrite
--                      the learner's own history.
--   entry_ids          jsonb array of uuid strings, in selection order. jsonb
--                      rather than uuid[] because it round-trips byte-identical
--                      through the client's `JSONValue.array(.string(…))` —
--                      `uuid[]` would come back lowercased while Foundation's
--                      `UUID.uuidString` is uppercase, a pointless diff to
--                      reconcile. Order is meaningful (selection order), and a
--                      json array preserves it.
--   updated_at         client clock (merge input — see SyncMergeRules)
--   deleted_at         tombstone (null = alive)
--   server_updated_at  SERVER clock — the column the pull paginates on. Never
--                      the client's: see the baseline migration's header for
--                      the full reasoning (a phone with a wrong date could
--                      otherwise write a cursor into the past or the future).

create table if not exists public.text_imports (
  id                uuid not null,
  user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title             text not null default '',
  content           text not null,
  source            text not null default 'paste',
  created_at        timestamptz not null default now(),
  coverage          double precision,
  entry_ids         jsonb not null default '[]'::jsonb,
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  server_updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

-- ---------------------------------------------------------------------------
-- Server clock trigger
-- ---------------------------------------------------------------------------
--
-- `public.touch_server_updated_at()` already exists (baseline migration); this
-- only attaches it. Dropped first so a replay re-creates rather than errors.

drop trigger if exists text_imports_touch_server_updated_at on public.text_imports;
create trigger text_imports_touch_server_updated_at
  before insert or update on public.text_imports
  for each row execute function public.touch_server_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
--
-- Same four policies as every other table, and they matter more here than
-- anywhere else: this is the only table that stores prose the learner wrote or
-- photographed. `using` decides which rows you may touch; `with_check` decides
-- what a row may look like afterwards — without it, a caller could update a row
-- they own and hand it to somebody else by rewriting `user_id`.

alter table public.text_imports enable row level security;

drop policy if exists text_imports_select_own on public.text_imports;
drop policy if exists text_imports_insert_own on public.text_imports;
drop policy if exists text_imports_update_own on public.text_imports;
drop policy if exists text_imports_delete_own on public.text_imports;

create policy text_imports_select_own on public.text_imports
  for select using (auth.uid() = user_id);
create policy text_imports_insert_own on public.text_imports
  for insert with check (auth.uid() = user_id);
create policy text_imports_update_own on public.text_imports
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy text_imports_delete_own on public.text_imports
  for delete using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Index
-- ---------------------------------------------------------------------------
--
-- The keyset walk the pull actually performs:
-- `order=server_updated_at.asc,id.asc` scoped to one user by RLS — see
-- `PostgRESTPullTransport.keysetFilter`. Only this one: the baseline's separate
-- `(user_id, server_updated_at)` index is a covered prefix of it, and exists
-- there only because that file reproduces history rather than tidying it.

create index if not exists text_imports_keyset_idx
  on public.text_imports (user_id, server_updated_at, id);
